[project]
name = "mypkg"
version = "0.0.0"
description = "mypkg"
authors = [{ name = "Me", email = "me@mycompany.com" }]

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]